# This is a basic workflow to help you get started with Actions

name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨執行

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: 'main'  #分支 main

    - name: Sync with upstream
      uses: aormsby/fork-sync-with-upstream-action@v2.1
      with:
        upstream_repository: "ChrisTitusTech/winutil"
        upstream_branch: "main"
        target_branch: "main"
        git_pull_args: "--ff-only"
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Push changes
      run: |
        git push origin main
